http:
  routers:
    my-service:
      rule: "Host(`my-service.intra`)"
      service: my-service
      entryPoints:
        - websecure
      tls:
        certResolver: step

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://my-service:80"
