services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped

    volumes:
      - ./step:/home/step

    networks:
      my-net:
        ipv4_address: 172.30.0.4

    dns:
      - 172.30.0.53

networks:
  my-net:
    external: true
